In [1]:
# 导包和拿数据集
import numpy as np
from math import sqrt
from collections import Counter
from sklearn.datasets import load_iris
iris = load_iris()
logits = iris.data 
labels = iris.target
print(logits[:2])
print(labels[:2])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]
[0 0]


In [2]:
# 常规操作，划分数据集
def train_test_split(X , y , test_ratio = 0.2 , seed = None):
    assert X.shape[0] == y.shape[0] , '特征和标签的长度要相同'
    assert 0 <= test_ratio <= 1 , 'test_ratio参数要符合规范'
    
    # 随机种子
    if seed:
        np.random.seed(seed)
        
    shuffled_indexes = np.random.permutation(len(X))
    test_size = int(len(y) * test_ratio)
    test_indexes = shuffled_indexes[:test_size]
    train_indexes = shuffled_indexes[test_size:]
    
    X_train = X[train_indexes]
    y_train = y[train_indexes]
    X_test = X[test_indexes]
    y_test = y[test_indexes]
    
    return X_train , X_test , y_train , y_test

X_train , X_test , y_train , y_test = train_test_split(logits , labels , test_ratio = 0.2)

In [3]:
# 实现knn
k = 3
y_predict = []
for x in X_test:
    distances = [sqrt(np.sum((x_train - x) ** 2)) for x_train in X_train]
    nearest = np.argsort(distances)
    topK_y = [y_train[i] for i in nearest[:k]]
    vote = Counter(topK_y)
    y_predict.append(vote.most_common(1)[0][0])
y_predict = np.array(y_predict)
y_predict[:10]

array([1, 2, 0, 0, 2, 2, 0, 2, 1, 2])

In [4]:
# 预测模型准确度
score = np.sum(y_test == y_predict) / len(y_test)
score

0.9333333333333333